#ansible-playbook -i invfile Playbooks/vault_testing.yml -vv --ask-vault-pass
---
  - name: Run AWS Cli Commands On All Servers
    hosts: privateserversip
    gather_facts: yes
    become: yes
    become_user: root
    serial: 3
    vars:
     user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61376362373264666261393135323336306531633831376465303735613839633466383834666338
          6465386531343262663466646263633936366336346430310a623664623030356362343432303233
          33343263643938626139383533376634623938343565623039376262636465653065353663653036
          6464336139373437660a393731633839393138336165313564633365343836663734323233383636
          3036
    tasks:
       - name: Create .aws folder
         shell: mkdir -p /root/.aws
         ignore_errors: yes
       - name: Copy Encrypted File To /tmp
         copy:
           src: /tmp/aws_creds #This Encrypted File Must Be Created Prior To Running The Playbook.
           dest: /tmp/aws_creds
           owner: root
           group: root
           mode: '0600'
       - name: Copy Encrypted File To .aws folder
         copy:
           src: /tmp/aws_creds #This Encrypted File Must Be Created Prior To Running The Playbook.
           dest: /root/.aws/credentials
           owner: root
           group: root
           mode: '0600'
       - name: Check S3 Buckets
         shell: aws s3 ls | cut -d " " -f 3
         register: buckets
       - name: Get VPCS
         shell: aws ec2 describe-vpcs | jq ".Vpcs[].VpcId" -r
         register: vpcs
       - name: Print VPC ID
         debug:
          var: vpcs        
       - name: Creating admin "{{item}}"
         user:
           name: "{{item}}"
           state: present
           comment: Admin User "{{item}}"
           groups: root
           shell: /bin/bash
           group: sudo
           password: "{{ '%s' | format(user_password) | regex_replace('\n', '') | password_hash('sha512') }}"
           password_expire_min: 1
         with_items:
         - anand
         - bala
         - chandra
         - david
       - name: Replace Password Authentication To Yes
         ansible.builtin.lineinfile:
           path: /etc/ssh/sshd_config
           regexp: '^PasswordAuthentication no'
           line: PasswordAuthentication yes
           backup: yes
         notify:
         -  Restart SSH Service
    handlers:
      - name: Restart SSH Service
        shell: service sshd restart