---
- name: play to install nginx on Linux servers
  hosts: publicserversip
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    KOPS_VERSION: '1.2.6'
  tasks:
  - name: check ubuntu version
    shell: cat /etc/lsb-release | grep DISTRIB_DESCRIPTION | cut -d "=" -f2 | tr -d '"'
    register: version
    no_log: true

  - name: print output
    debug: 
      var: version
    no_log: true

  - name: perform apt update
    shell: apt update && install -y unzip net-tools

  - name: install nginx
    apt: 
      name: nginx
      state: latest
